name: Sheet Monitor

on:
  workflow_dispatch:  # 外部からの手動実行用（ZapierやGASで使用）

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run monitoring script
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          SPREADSHEET_KEY: ${{ secrets.SPREADSHEET_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python main.py
